import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import 'react-loading-skeleton/dist/skeleton.css';
import ProviderComponent from './components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Forum Discussion Alterra',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ProviderComponent>
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </ProviderComponent>
  )
}
